### ISSUE TITLE
Iterative algorithms checklist

### ISSUE THREAD

**Issue by ocramz** [ocramz/sparse-linear-algebra#61]
From https://github.com/JuliaMath/IterativeSolvers.jl/issues/1 

A comprehensive listing of methods in the references.
Please remove any methods are impractical/obsolete and add methods worth implementing to the list.

Linear systems

    Stationary methods
        - [ ] Jacobi (LT)
        - [ ] Gauss-Seidel (LT)
        - [ ] Successive overrelaxation, SOR (LT)
        - [ ] Symmetric SOR (LT)
    Nonstationary methods
        - [ ] GMRES (LT, Saa)
        - [ ] MINRES (LT)
        - [ ] Conjugate Gradients, CG (LT)
        - [ ] LSQR
        - [ ] LSMR
        - [ ] BiCGStab(l) (Sle)
        - [ ] Chebyshev iteration (LT)
        - [ ] Quasi-Minimal Residual, QMR (LT)

(Generalized) eigenproblems

    Without subspace
        - [ ] (Shift-and-inverted) power iteration (ET)
        - [ ] Rayleigh Quotient Iteration [1]
    Krylov subspace methods
        - [ ] Implicitly restarted Lanczos (ET)
        - [ ] Implicitly restarted Arnoldi (ET)
    Other subspace methods
        - [ ] Jacobi-Davidson method (ET)
        - [ ] LOPCG
        - [ ] Accelerated Rayleigh Quotient Iteration [1]
        - [ ] (Shift-and-inverted) subspace iteration (ET)

Singular value decomposition

    - [ ] Golub-Kahan-Lanczos (ET)

References

    LT: Templates for the Solution of Linear Systems: http://www.netlib.org/linalg/html_templates/report.html 
    ET: Templates for the Solution of Algebraic Eigenvalue Problems : http://web.eecs.utk.edu/%7Edongarra/etemplates/book.html 
    Saa: GMRES: A generalized minimal residual algorithm for solving nonsymmetric linear systems (pdf) : http://www.stat.uchicago.edu/%7Elekheng/courses/324/saad-schultz.pdf 
    Sle: BiCGstab(l) and other hybrid Bi-CG methods (pdf) : http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.139.7946&rep=rep1&type=pdf 
    TB: Numerical linear algebra : http://www.worldcat.org/title/numerical-linear-algebra/oclc/36084666 
    HV: Iterative Krylov methods for large linear systems : http://www.worldcat.org/title/iterative-krylov-methods-for-large-linear-systems/oclc/837021440 

[1] Low-priority methods: they are quite expensive per iteration.

**Comment by GregVernon** [comment]
How about the recently developed Alternating Anderson-Richardson method?

_Alternating Anderson-Richardson method: An efficient alternative to preconditioned Krylov methods for large, sparse linear systems_  https://arxiv.org/abs/1606.08740

**Comment by ocramz** [comment]
Alternating Anderson-Richardson method: An efficient alternative to preconditioned Krylov methods for large, sparse linear systems https://arxiv.org/abs/1606.08740
